# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61222a066bdbbbc9f8b5d5006deaac2b56319b927a8bf717a184e0eba15f4b6c2f516ac819ea53ad794668f2d1b125dce51aa2661149cdd83db57801a30b3418

test:
  secret_key_base: 88c7513a1006a1dd78cd72a39c7a1c47af64d1d58d5bce40090cf0b7979df0f83dfbc3516f5db512c50575cf7d9e5655750bbc05bc4840f07308432e74d71403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
